### ISSUE TITLE
order cohorts by school

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1039]
in the course manager cohort selection list, the programs currently do not sort by school. To improve usablity, they should. So instead of:

> Medicine|MD
> > 2014
> > 2015

> Pharmacy|PharmD
> > 2014
> > 2015

> Medicine|PhD
> > 2014
> > 2015

> Dentistry|DDS
> > 2013

the user should see

> Dentistry|DDS
> > 2013

> Medicine|MD
> > 2014
> > 2015

> Medicine|PhD
> > 2014
> > 2015

> Pharmacy|PharmD
> > 2014
> > 2015

**Comment by dartajax** [comment]
@saschaben I was using the application today and was contemplating an issue regarding this into github as well but we can talk about it here since this is basically the same issue.  Wouldn't it be better if you are adding a Course to 2015-2016 in the School of Medicine that the School of Medicine would appear first and Doctor of Medicine 2015-2016 would be the default or at a minimum the easiest one to select?  Also, the earlier years probably should not all be included.  I understand there needs to be flexibility here but the user has already selected the school and academic year so DDS 2012 would not really be needed.

**Comment by dartajax** [comment]
Maybe we could have all cohorts that could possibly be attached to School of Medicine 2015-2016 be displayed.  And maybe a "More" button or something to open up other schools and years?  Anyway, that's just what I thought with my user hat on.  

Adding a cohort is basically the first thing a course coordinator would do no?  There really is no reason to have the session information even available since you can't do anything there without a cohort.  It should be more obvious in the interface if / when a cohort is missing.  My $.02.
