### ISSUE TITLE
Session Delete Fails

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1280]
![image](https://cloud.githubusercontent.com/assets/7493331/11982503/a0e65d20-a960-11e5-89a8-020aa4f21950.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11982513/b7c6c1b0-a960-11e5-9ca9-840f9ba10deb.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11982519/c89e6f4c-a960-11e5-8b78-19c3c7b2f040.png)

Refresh the screen - Session still there - Delete action fails.

**Comment by jrjohnson** [comment]
Just a note: This is almost certainly due to the attached offering. Or another relationship that isn't setup to cascade in the database.  We will have to decide if we want the delete to cascade, or if we should prevent the delete from the user and show the a message about why.

**Comment by dartajax** [comment]
I was in a meeting with SOP today and the session they wanted to delete did not have an offering.

**Comment by jrjohnson** [comment]
Might be an offering, and instructor group, and objective, any one of the relationships could be the issue.

**Comment by saschaben** [comment]
On delete options: keeping in mind the Prime Directive ("How does this make for a better experience for the student / instructor / supporting staff?"), we should focus on providing a model for the deletes to cascade, and look to provision the delete function according to role/permission, rather than being stymied by attached or associated attributes to the item being deleted.

**Comment by stopfstedt** [comment]
don't forget session description, deletes on owning sessions do not cascade down to descriptions either.

i'd favour implementing cascading deletes on sessions over having users delete all associated data points manually.

@jrjohnson @saschaben thoughts/opinions?

**Comment by stopfstedt** [comment]
duplicates ilios/ilios#1231
