### ISSUE TITLE
Provide ability to link sessions within a course

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1323]
see ilios/ilios#822. This is particularly pertinent to ILMs being associated to other sessions as prerequisites.

**Comment by saschaben** [comment]
DUE BY APRIL 15 2016

**Comment by saschaben** [comment]
For the UI, the current "Due By" label is replaced by a toggle. State 1 is the current status quo:
![ilmdueby](https://cloud.githubusercontent.com/assets/1753431/16135876/4e0b5ad2-33db-11e6-98ab-344ecd0b3865.png)

State 2 replaces the calendar/date picker with a drop down select list of all the current sessions in the course:
![ilmduebefore](https://cloud.githubusercontent.com/assets/1753431/16135938/914299d2-33db-11e6-9180-7b5d852e858f.png)

Future states may require the extension to select sessions from other concurrent courses in the program.

**Comment by saschaben** [comment]
This would also predicate a new way of expressing this info in the calendar/agenda displays and calendar event page. A new section, like "learning materials" could be added to the event page, called "pre-work" or "pre-requisites" or something similar. Would provide descriptive title link to the required object/ILM/Session, which in turn would now also display a link to the target session, "Due by [date of offering for current user] - [descriptive title link]"

**Comment by saschaben** [comment]
Questions for display: 
what is the desired view in the ics feed to identify linkage?
what is the desired view in Week at a Glance?
what is the desired view in the calendar grid?

ILMs (for example) currently display at 5pm on the day due. If we have 5 ILMs all linked to one another with the same due date....do they stack in order? does it matter?

**Comment by saschaben** [comment]
what ILMs will look like in calendar:

![ilm-multiday](https://user-images.githubusercontent.com/1753431/46692509-5549f300-cbbc-11e8-83bb-911b3ac3e0ba.png)

what ILMs will look like in WaaG:

![ilm-multidaywag](https://user-images.githubusercontent.com/1753431/46692510-5549f300-cbbc-11e8-83c5-17967b512af0.png)

**Comment by saschaben** [comment]
Adding a linked session (non-ILM)

![sessionbase](https://user-images.githubusercontent.com/1753431/46749588-ee374780-cc6a-11e8-89f1-01d5b740062f.png)

Event Display for linked non-ILM

![courselinkevent](https://user-images.githubusercontent.com/1753431/46750049-f17f0300-cc6b-11e8-8179-301342ef36d1.png)

Event Display for linked ILM

![ilmlinkevent](https://user-images.githubusercontent.com/1753431/46750560-14f67d80-cc6d-11e8-96f4-9d57094ee269.png)

**Comment by jrjohnson** [comment]
Notes from code jam:

When prerequisites have prequisites each one should roll up to the final event

so Neuro -> Coma -> Health -> Community 

Would end up as 

Neuro
	Community
	Health
	Coma

In order to load all of these possibly deeply nested events we should
load a users entire event space first and then filter down.
So DB query loads everything for all of time
then we filter out what we want, but keep the event nest
then we go back through and re-nest all postrequisites

The final userevent will be a super deeply nested set of events going all the way down

```
<PrerequisiteEvent @event={{event}} />
	{{#each @event.prerequisite as |event|}}
		<PrerequisiteEvent @event={{event}} />
	{{/each}}
	Title
```

This puts the next level of prereqs above the owning level


OPTION 2 (THE FINAL OPTION)
Leave all of the events on the week at a glance page and anchor tag link
between them on that page. When following a title link it would go to the 
single event page. Very little changes in the UI.
For the anchor tag we can use the session id plus a time stamp.


About Publication:
If an ILM is published, but it's linked session is not it would fail to show up 
in the Week at a Glance. To prevent this we should not allow sessions to be published
unless all of their prereqs are published. In the UI we should add this to the publication 
check.
