### ISSUE TITLE
Hide the Lower Panes When Multi-Edit in Learner Groups Is Selected, and refactor groups management

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1506]
Currently when you switch on the Multi-Edit functionality in Learner Group Maintenance, it only activates the top pane to be able to multi-select.  The label should change as well to something like "Sub-Group Assignments" since once you select multi-edit, all of the sub group assignments appear in the top pane for maintenance.

top pane activated containing all of the functionality of the lower panes ...

![image](https://cloud.githubusercontent.com/assets/7493331/13993289/f8e72978-f0dc-11e5-8c21-08eac5211db9.png)

lower panes not needed anymore ...

![image](https://cloud.githubusercontent.com/assets/7493331/13993319/1792416e-f0dd-11e5-8e8a-7b8bb24386fa.png)

**Comment by dartajax** [comment]
This mostly applies in the "Cohort Members NOT assigned to ..." area since there may be an entire cohort down there that needs to be added to groups and / or sub-groups.

**Comment by saschaben** [comment]
Additionally:

- [ ] add breadcrumbing
- [ ] allow sorting of names
- [ ] default to multi-edit
- [ ] add search
- [ ] provide more constrained list for multi-edit "select all"

**Comment by jrjohnson** [comment]
@saschaben / @dartajax  if we default to multi edit in the top box then are the bottom panes redundant?  Should they be changed instead to be lists of the users in those places with links to the groups they are in as opposed to being the place where edits can be made?

**Comment by jrjohnson** [comment]
What does the more constrained select all look like?  I'm assuming just people in the tree excluding those in the cohort?

**Comment by jrjohnson** [comment]
Do we need to be able to sort names in multi-edit mode?  Or is that just in the bottom two boxes?

**Comment by saschaben** [comment]
@jrjohnson Great questions for my vague definitions! Here are a few initial answers, leading to (of course) many more questions:

 > _if we default to multi edit in the top box then are the bottom panes redundant?_ 
 >> I'm not sure about this one; on the one hand, yes, they become redundant, but if they become only lists, will they serve a value purpose? Hence my thought of just collapsing them to clean up the contextual view of the page, and worry about functionality later....?

 > _What does the more constrained select all look like? I'm assuming just people in the tree excluding those in the cohort?_
 >> That is correct.

 > _Does add search mean add filtering to the list of users? Which list (all three?)_
 >> That is correct. And I think yes, on all lists.

 > _Do we need to be able to sort names in multi-edit mode? Or is that just in the bottom two boxes?_
 >> If we have filtering in the multi-edit box, we may be able to get away without sort there.

**Comment by jrjohnson** [comment]
@saschaben I'm considering having two views on this page.  The initial view would present our current four boxes as lists of users with a filter at the top of the page to find a specific user.  Then we could have an edit mode which would be the bulk edit box we have now, but expanded to fill the while page since everything else could be turned off.

I think this would clean up the page quite a bit, but it would remove the ability to move a single user around without opening the multi-edit option.

Does that make sense?  Is it a terrible idea?

**Comment by saschaben** [comment]
I think we need to mock it up before going that route, and talking it through with at least one user rep (maybe get mocks together and invite valentina?)

Let me get started on some page mocks

**Comment by saschaben** [comment]
OK. So here's a start: what if we had a landing mode, which showed essentially what we have now, but with single line edits in the main (upper list) gone, and instead of the single line edit listings in the middle box, display the members of each sub group with the eyeball inspector. The "Not in Group" list remains at bottom:
![group-nonedit](https://cloud.githubusercontent.com/assets/1753431/14507446/854e41e4-0177-11e6-828f-10505d8be42e.png)
This would mean that there would not be any "global" search filter for users, though. So this might not fly.
in "edit" mode, we would: turn on the existing multi-edit view (less the "not in this group" listings); collapse the container with the subgroups, and activate the line by line links to move people from "not in this group" to the group/subgroups:
![groupedit](https://cloud.githubusercontent.com/assets/1753431/14507435/7e3eb78a-0177-11e6-8ce1-10eb6c5155b1.png)
The upside of this model is that it better matches existing patterns, it consolidates the edit functions, reduces the page size, and (I think) clarifies for the user what is going on. The downsides are that I'm not sure of the technical complications this might introduce, it loses the ability to introduce global search, but other than that nothing is coming to mind. @jrjohnson thoughts?

**Comment by jrjohnson** [comment]
Think this might be the sweet spot. Looks very nice. Do you want to run it past anyone static it should I go ahead and build it?

**Comment by saschaben** [comment]
I'd like to get some input from valentina or kylie or Padric before we commit to this route. Let me see if I can corral an opinion today, and let you know.

**Comment by saschaben** [comment]
and in further thought: perhaps the edit mode for "not in group" list should simply provide an "add to current group" button that would instantly move that user from the list to the currently displayed group (eg, if I'm looking at Anatomy, they'd shoot to Anatomy. If I'm drilled down to Anatomy > Anatomy Lab 4 > Cadaver Group, they'd shoot straight to Cadaver Group, and so on).

Also, without knowing the tech constraints, is it possible to provide sorting and also filtering to the top box in both non-edit and edit modes, in a way that would persist between modes (ie, I sort by last name, and filter for jones in non-edit, see the guy I'm looking for, swith to edit, and STILL see the same sorted/filtered list...)?

**Comment by jrjohnson** [comment]
Yes.  Lets make the top box a table and in non edit mode it would have sorting, filtering, etc... and then in edit mode it would be nearly the same with the addition of check boxes as well as a dropdown to place the checked people in.  Could look a lot like the unassigned students in cohorts display.

I completely agree with changing the click and select to move a person somewhere to a button to move them to HERE is a way better idea.
