### ISSUE TITLE
Missing Translation -- Add New User - User Exists

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1584]
![image](https://cloud.githubusercontent.com/assets/7493331/14501622/2eca0e54-015c-11e6-932a-703674c60616.png)

The callout on mouse-over states ...

`Missing translation: admin.gotToUser`

It should probably explain that the user already exists in Ilios or something like that, no?

**Comment by dartajax** [comment]
Actually it looks like `gotToUser` should be `goToUser` yes?

**Comment by saschaben** [comment]
should be "user record is already in Ilios" (FR: "Utilisateur existe déjà en Ilios")

**Comment by jrjohnson** [comment]
Translation already exists at https://github.com/ilios/frontend/blob/master/app/locales/en/translations.js#L544

We're just asking for it inncorectly.  Fix is to change https://github.com/ilios/frontend/blob/master/app/templates/components/new-directory-user.hbs#L158 to use goToUser instead of gotToUser.
