### ISSUE TITLE
Deactivate disabled users in the user-search results

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#162]
I noticed this when we were looking at course directors; but it should be applied anywhere user records are pulled up -- instructors, student groups,etc.

**Comment by saschaben** [comment]
actually, it's more subtle: disabled accounts should be returned, but need to be identified. See learner group listings in 2.4.8 for examples. disabled students are grey/italic. 

If a user is attached to a curricular object and is later disabled, we do NOT want that user record to vanish -- we only want to note that it is not currently available for selection to something new. So instructor assignment lists would not include disabled users, but a disabled instructor attached to last years course would still display. Student assignment lists should actually include disabled students --- since they may still be required to be added to a group or managed, despite their account status.
