### ISSUE TITLE
"Add New",  "New Session", "Print Summary" buttons styled differently

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#172]
we gots a lot of different color blues and different heights on our action buttons. let's make them consistent.

**Comment by jenzweben** [comment]
Print Summary is a different color blue by design.  However, all buttons that are Add or New should be $ilios-blue.

I'm creating a new button to address the issue that the Add New buttons on the Course Detail Page have issues - the Add New buttons are not inheriting style eventhough we have added the reset button code.

**Comment by jenzweben** [comment]
I have created a new issue to address the "New Session" styling & terminology #182
