### ISSUE TITLE
Natural Sort Needed in ILM Learner Group Picker

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1776]
I don't know how easily this can be accomplished.

It would be helpful to see the groups in a more logical order ...

BMB FPC Small Group 1
BMB FPC Small Group 2
BMB FPC Small Group 3

... like what is indicated above rather than ...

![image](https://cloud.githubusercontent.com/assets/7493331/16017421/a0ac84c0-3154-11e6-8705-56874062ffb0.png)

**Comment by stopfstedt** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Numeric_sorting

alas, it's not supported by mobile browsers. will check if this is the solution for desktop browsers, and if so, how this plays out on mobile (whether this degrades gracefully or throws errors if options are passed to `localCompare()`).

**Comment by stopfstedt** [comment]
found this as well: https://www.npmjs.com/package/natural-orderby

not convinced that this issue would warrant adding a dedicated library to our dependencies, but probably still worth a look.

**Comment by jrjohnson** [comment]
We're using `localeCompare` a couple of places https://github.com/ilios/frontend/blob/master/app/components/ilios-course-list.js#L98 without options. If I'm interpreting the MDN doc correctly it is saying that if we don't provide the options that the browser will pick. I'm guessing it will choose based on the `lang` property of our `index.html` which should match the users selected language anyway so this might be fine. Otherwise it might default to `en` and that wouldn't be terrible either.

**Comment by stopfstedt** [comment]
not actively working on this, so i unassigned myself from this ticket.
