### ISSUE TITLE
Improve loading of instructor groups list

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#1799]
Currently the group load every offering to get summary counts.  Can we speed that up?

**Comment by stopfstedt** [comment]
not an offering-form related issue, so i'm removing this from the meta ticket list.

**Comment by stopfstedt** [comment]
the issue here is that in order to show course totals, we not only have to load each offering and ilm that any given instructor-group is associated with, but also all ilm/offering-owning sessions and finally all session-owning courses. ember-data already does its best to group those requests, i'm not convinced that we can significantly reduce churn here.

therefore i'm proposing to side-step this issue and just ditch the associated courses column from that table. the information on associated courses is displayed on instructor group details already as well. 

alternatively, we could do the lookup server-side and push the course count as a read-only data point. i'm not liking this idea.
