### ISSUE TITLE
Clean Up Admin Console Styling

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1806]
a first iteration:
![newadmin](https://cloud.githubusercontent.com/assets/1753431/16202960/de54a852-36cc-11e6-9cd6-47ba9a279a80.png)

user list would NOT necessarily load on landing --- just showing where it would load in the page.

**Comment by jrjohnson** [comment]
Discussion:
Admin dashboard gets a row for user management which looks like the top of @saschaben's screen shot.  It has a 'Manage Users' button a search box and collapsed indications of the user updates and alerts boxes.  Clicking any of these things (or searching for a user) open the user list underneath with the results of your action.  This would happen instead of visiting a different route.

**Comment by jrjohnson** [comment]
Fixed in #1810
