### ISSUE TITLE
Course Rollover needs instructional text

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#1833]
The course rollover process in the GUI needs instructions on how to use the rollover, including how entering the start date will shift all associated offerings in conjunction to that start date's week and that the start date needs to be on the same day as the original course's start date's day of week. Also, maybe list the original course's start day in the instructional text or near the text field.

**Comment by saschaben** [comment]
"Please note: in order to maintain integrity, rollover course start dates must be the _same day of week_ as the original course. Changing the start date will appropriately shift all offerings to the corresponding week of the course.

"If you are rolling over a course into the same Academic Year as the original, or if a course of the same name already exists in your target year, please modify the course name prior to selecting your target year and hitting the 'Done' button."

**Comment by dartajax** [comment]
Steps ...

![image](https://user-images.githubusercontent.com/7493331/56840946-77951c80-683f-11e9-9ae7-8ac9a0114c5d.png)

After clicking as shown above ...

![image](https://user-images.githubusercontent.com/7493331/56840963-95fb1800-683f-11e9-8f23-a658fbf3a035.png)

The instructional message on the second screen shot should be updated to the text that is in this ticket up at the top of it.

**Comment by dartajax** [comment]
All the information in this ticket is provided to the user if `Advanced Options` is clicked. If the user simply rolls over the course, an appropriate start date of the newly created, rolled over, course is generated by the system automatically - and it is the correct day of the week.

I am thinking we can close this ticket after a brief team discussion - hence my tagging and self-assignment of the ticket.

**Comment by jrjohnson** [comment]
Closing re: @dartajax as instructions are available elsewhere on the screen.
