### ISSUE TITLE
Icons periodically disappear

### ISSUE THREAD

**Issue by justinchu17** [ilios/frontend#1864]
Sometimes icons seem to go away, and then after a while they come back.
![missing ilios 3 icons](https://cloud.githubusercontent.com/assets/11322104/16849393/1a546fe6-49af-11e6-9efe-8ae3753db7dc.PNG)

**Comment by mtb3** [comment]
I have also encountered this problem using Chrome on Mac OS, and it was also reported to me by a user on Internet Explorer 11 on Windows 7.

I believe the issue may be caused by Cross-Origin Resource Sharing issues with CDN-sourced FontAwesome icon font. I will try to add more details when I get a chance...

**Comment by jrjohnson** [comment]
The solution to this seems to be doing away with our font awesome icons and using SVGs instead. 
Steps:
- [ ] Generate SVGs from the icons we currently user
- [ ] Create n easy process for adding new icons
- [ ] add https://github.com/ivanvotti/ember-svg-jar to help us organize and see our SVGs.
