### ISSUE TITLE
Create Ilios Dashboard Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#206]
Hi Sascha - here's a draft of the dashboard.  It's showing the state where a user is adding a new report.  It expands down (which would push Your Alerts and Calendar sections down).  Please review and then we can discuss and I'll revise...Thanks!

![ilios-dashboard](https://cloud.githubusercontent.com/assets/5023894/6356036/79a02c12-bc0f-11e4-890e-0478eea9ccba.png)

**Comment by saschaben** [comment]
Forgive my awesome graphical talents. How about shifting this slightly, to provide a calendar view toggle at the top of the page?
![79a02c12-bc0f-11e4-890e-0478eea9ccba](https://cloud.githubusercontent.com/assets/1753431/6357974/47322736-bc1d-11e4-9a6f-9d25bc0278c7.png)

Also: Your alerts requires an "add new" feature.

@jenzweben can you re-mock to show this? And also a mock with the expanded calendar, including the search and filter tools?

Really, really like this so far!

**Comment by jenzweben** [comment]
bonjour - @saschaben - I like your dashboard mockregarding the show/hide calendar functionality…would you want the calendar to display at the top or the bottom? I’m interpreting the state shown in your mock as the events view…

**Comment by jenzweben** [comment]
![ilios-dashboard-v2](https://cloud.githubusercontent.com/assets/5023894/6361108/383a44cc-bc34-11e4-8a05-c21a44109acf.png)

**Comment by saschaben** [comment]
@jenzweben calendar at top, I think. My events list block should be a static block, like recent activity etc., turning on the calendar would either plug the calendar in at top of page right above it (pushing everything down), or replace it, pushing everything down.

There is some value in providing both the List For The Week, as well as the graphical display, but I keep going back and forth in my head about this...in any case: calendar at top, calendar "off" displays list as you have rendered, calendar "on" displays graphical calendar at top of page, either on top of or instead of list.

**Comment by jenzweben** [comment]
Updated Calendar Off State (default)
![ilios-dashboard-v3-calendar-off](https://cloud.githubusercontent.com/assets/5023894/6380962/8c9bf90c-bcf2-11e4-9639-11fd7492342e.png)

**Comment by jenzweben** [comment]
Calendar On State

![ilios-dashboard-v3-calendar-on](https://cloud.githubusercontent.com/assets/5023894/6380970/9a990f0e-bcf2-11e4-8584-3774f95be518.png)

**Comment by saschaben** [comment]
@jenzweben looks good. @jrjohnson we will need to discuss what data to display in the event list, but I think this is looking close to just about right. thoughts?

**Comment by saschaben** [comment]
On further consideration: event listing should show:
>>Date - Start Time & End Time (or duration if ILM) - Session Title - Location - Course Title - Session Type.
Level is not needed. If space constraints are an issue for text, course title could also potentially be dropped.

**Comment by saschaben** [comment]
MY COURSES:

for educators and learners: courses to which I am associated and with a start date which has passed or will occur within ten days, and with an end date that has not passed or passed within ten days.

**Comment by jenzweben** [comment]
First draft for filters open
![ilios-dashboard-v4-filters](https://cloud.githubusercontent.com/assets/5023894/7849051/2de70e0c-0486-11e5-9bf7-c803d54f7b0b.png)

**Comment by jenzweben** [comment]
First draft for filters open

![ilios-dashboard-v4-filters](https://cloud.githubusercontent.com/assets/5023894/7849109/b9d8ba1e-0486-11e5-917e-084809aeff70.png)

**Comment by saschaben** [comment]
@jenzweben for calendar filters, don't forget to provide a slector . space for a selector for school. Additionally, they also need the ability to filter by course/session type. The current version allows them to toggle between that and the state you have mocked.

**Comment by jrjohnson** [comment]
Wow.  Its great when @jenzweben takes my stupid suggestion and turns it into a great idea.  I like this, I think it fits in the space we have and I think with the calendar underneath it is clear what it does.

I'm not sure what the save / undo buttons at the top do.  If they apply the filters I think we should try it as a live every time you click it filters action to see how fast it is before adding an apply button.  Then you can watch the calendar underneath changing.

I think the day / week / month controls should go underneath the filters since they control that display right there.

What does the other side of the My Schedule slider say?

**Comment by jenzweben** [comment]
Updated filters on Topics / Details (vs. Courses) mock:
![ilios-dashboard-v4-filters-topics](https://cloud.githubusercontent.com/assets/5023894/7864881/bb80839a-0519-11e5-974c-ed19c0cd3099.png)
I'll delete the previous mock to try to avoid confusion

**Comment by jenzweben** [comment]
Updated filters on Topics / Details (vs. Courses) mock:

![ilios-dashboard-v4-filters-topics](https://cloud.githubusercontent.com/assets/5023894/7865006/7fc85908-051a-11e5-9419-628465dfa164.png)

I removed the previous mock to avoid confusion

**Comment by jenzweben** [comment]
Default state (Hide Filters) 

![ilios-dashboard-v4-default](https://cloud.githubusercontent.com/assets/5023894/7865031/ba4845d4-051a-11e5-9c83-0d7eb7da87d6.png)

**Comment by saschaben** [comment]
filter label texts:

 on state | off state 
------------|--------------
SHOW | HIDE 
TOPIC / DETAIL | COURSE / TYPE 
MY SCHEDULE | SHOW ALL

**Comment by jenzweben** [comment]
I'm confused - isn't course/type another filtering option?  so the filters would have to be on...

**Comment by saschaben** [comment]
per your mock, the topic/detail - course/type and my schedule/show all toggles only appear when the filter toggle is set to "show". so the "on" state of the other two would be their default state (or the opposite), and they would be green-blue toggles, not green-grey on off switches....

**Comment by saschaben** [comment]
![7fc85908-051a-11e5-9419-628465dfa164 png 1280x2424 2015-05-28 11-12-18](https://cloud.githubusercontent.com/assets/1753431/7867406/cd3c8a14-052a-11e5-8f89-a13533a969f9.png)

**Comment by jenzweben** [comment]
How will the user know that their search has been saved if we don't have the red/green buttons...

**Comment by saschaben** [comment]
good point, but we will have to discuss the mechanism for saved search; since it isn't current functionality we may want to just focus on getting this out, and gearing saved issues to the My Reports section. We could also look at using a flash alert with a save button, or something along those lines.

**Comment by jrjohnson** [comment]
Saved search isn't an option we can make happen without a schema change so it will have to be a future feature.  For now filtering the calendar should be transient.

**Comment by jenzweben** [comment]
Alrighty - makes it easy :)

**Comment by jenzweben** [comment]
Filters on:
![ilios-dashboard-v4-default](https://cloud.githubusercontent.com/assets/5023894/7886875/e2b4ec44-05e1-11e5-8554-add366fba8f0.png)


Filters off (default):

![ilios-dashboard-v4-default](https://cloud.githubusercontent.com/assets/5023894/7886882/edf15caa-05e1-11e5-919a-3097de96ce51.png)

**Comment by saschaben** [comment]
@jenzweben I think you misunderstood my comment about day-week-month: my thought was that they should be closer to the actual calendar grid, and below the filters when on, since they are a control for changing the calendar grid viewing pane, really. Moving them into the header certainly looks good, but moves them even farther away from their functional context.

**Comment by jenzweben** [comment]
doh!

**Comment by jenzweben** [comment]
Filters Off (default):

**Comment by jenzweben** [comment]
Filters Off (Default):
![ilios-dashboard-v4-default](https://cloud.githubusercontent.com/assets/5023894/7917986/2e073770-0843-11e5-83d0-53a6a60f5e5e.png)

Filters On:
![ilios-dashboard-v4-filters-topics](https://cloud.githubusercontent.com/assets/5023894/7917999/36743bba-0843-11e5-8e84-31e644124361.png)

**Comment by dartajax** [comment]
I was showing this to Valentina and she had a couple of suggestions that I am just going to write down here but could move to or add to #746 or one of these other tickets if need be - or create a new ticket.  But for now ...

* Search by Course should be the default on the Dashboard rather than search By Topic.  The order here is fine (First by Course and then by Session Type)
* If Search By Topic is selected, the search areas should be in the following order (they have been incorrect in Ilios 2.4.x - good time to re-vamp).
    * Level
    * Program / Cohort 
    * Session Type
    * Topic

**Comment by saschaben** [comment]
closing. Please reference individual tickets for remainder of work (#747 & #748). Items should be added to PRs and merged.
