### ISSUE TITLE
Session offering / group details in the list

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#226]
When a use clicks the offering count in a session list the table row should expand to list those offerings.  Much like the course delete confirmation works.

@jenzweben - please mock this up.

**Comment by jenzweben** [comment]
@saschaben please review and reassign to me with comments or assign to @jrjohnson if it's good to go:

![course-detail-session-offering-open](https://cloud.githubusercontent.com/assets/5023894/6403301/23fe5454-bdc3-11e4-8561-6c905ce3a300.png)

**Comment by saschaben** [comment]
I *think* I like this -- can we clean the mock so that it reflects consistent data? Can you mock up the following open panels in a session list:

Session A shows one group in the #Groups column, list one offering

Session B shows two groups in the #Groups column: provide two line item offerings for two different groups (same time block, differing location)

Session C shows two groups in the #Groups column: provide two line item offerings for two different groups (different time block, differing location)

session D shows five groups in the #Groups column, one offering for all groups together

I think we've covered the other variables well enough in the current mock.

**Comment by jenzweben** [comment]
![course-detail-session-offering-open-v2](https://cloud.githubusercontent.com/assets/5023894/6447324/3c93e3ac-c0c6-11e4-9cba-c5dc913c7aac.png)

**Comment by saschaben** [comment]
@jenzweben missing an end time on one of those, but otherwise, looks OK. Can you re-do the Tuesday with numerous simultaneous events in differing rooms to show the end time and repost?

**Comment by jenzweben** [comment]
![course-detail-session-offering-open-v2](https://cloud.githubusercontent.com/assets/5023894/6452244/3b08e3b6-c0e9-11e4-8894-a698cce1533e.png)
