### ISSUE TITLE
Better Labeling of School Level Competency Domains On Program Year Competency Management Needed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2340]
Follow the screen shots and squiggly arrows for illustration of this.

![image](https://cloud.githubusercontent.com/assets/7493331/20081467/af8cc5ee-a504-11e6-9ebd-d974283f2fbc.png)

![image](https://cloud.githubusercontent.com/assets/7493331/20081480/c0e79fc6-a504-11e6-8195-0b3ddeee057b.png)

![image](https://cloud.githubusercontent.com/assets/7493331/20081500/d0b1b6f8-a504-11e6-97c3-e83b38dc908d.png)

![image](https://cloud.githubusercontent.com/assets/7493331/20081508/e0f1f334-a504-11e6-9513-7d17b639387f.png)

![image](https://cloud.githubusercontent.com/assets/7493331/20081514/ecff2732-a504-11e6-8dd2-693b33bad548.png)

![image](https://cloud.githubusercontent.com/assets/7493331/20081527/089f274e-a505-11e6-93e1-5c09f420e02b.png)

![image](https://cloud.githubusercontent.com/assets/7493331/20081548/1c0dcc36-a505-11e6-9b56-2d2965966d82.png)

But look what happens ...

4 of them have now become unselected at the same time.

![image](https://cloud.githubusercontent.com/assets/7493331/20081562/36a2e838-a505-11e6-9ec6-1c0f34b211cf.png)

When selecting or deselecting any of the Program Year Competencies indicated by the blue squiggly lines, all of the subsidiary Competencies are selected or de-selected automatically.  Maybe we should bold these higher level School Competencies so the user will know why multiple selections are being selected or de-selected.

![image](https://cloud.githubusercontent.com/assets/7493331/20081701/1362e5e8-a506-11e6-87b4-1a520593291f.png)

**Comment by saschaben** [comment]
@dartajax this is actually the correct behavior; note that the checkboxes are tri-state, and the "-" is identified for top-level domains when their sub-domains are selected (but the parent is not) -- as well as when only some of the subdomains are selected. this could definitely use better labeling -- making top level domains bold in the select list as well as in the display list, for instance -- but this is apparently pretty challenging technically. I felt it was more important to get the functionality out there, and make the effort to explain it, rather than delay it while we tried to find a way to implement the CSS to make it play better.

The various states available:

the nice tidy list view:
![comp1](https://cloud.githubusercontent.com/assets/1753431/20084441/2bbd48e8-a517-11e6-988f-4600efb671d8.png)

these are sets of competencies where: all subdomains are selected, but the TOP LEVEL domain is NOT selected:
![comp2](https://cloud.githubusercontent.com/assets/1753431/20084439/2bbc008c-a517-11e6-9c8e-4fd6ff18cdca.png)

Here the entire set is unselected:
![comp3](https://cloud.githubusercontent.com/assets/1753431/20084443/2bc00344-a517-11e6-8bd2-17bc32fde6b2.png)

...and here the top level domain is selected, but NONE of the subdomains are selected:
![comp5](https://cloud.githubusercontent.com/assets/1753431/20084442/2bbf6592-a517-11e6-92c8-5b97f633ef56.png)

Here a single subdomain selected, as well as explicit selection of the top level domain:
![comp9](https://cloud.githubusercontent.com/assets/1753431/20084553/f59b8e54-a517-11e6-9919-b2abcc8f2f3b.png)

And finally, a few but not all of the subdomains selected, and the top level unselected:
![comp6](https://cloud.githubusercontent.com/assets/1753431/20084440/2bbd0824-a517-11e6-89f7-23b870bbc69c.png)

We assume that people will be able to follow, since the users who manage this will already know the model -- but we need to be clear in our description of it as well.

**Comment by dartajax** [comment]
I am glad we are keeping the ticket open just for reference.  Thank you @saschaben for pointing all that out.  Also, when you create a new program year, the competencies are copied from the previous year anyway.
