### ISSUE TITLE
Make in place objective manager expansion a query param

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#255]
Currently changing from viewing the list of objectives to managing the parentage of a single objective is not reflected in the query params for the course route.  This means that when someone refreshes or hits the back button they will not get consistent behavior.  By setting the currentlyManagedObejctive as part of the route query parameters we can fix this.

**Comment by saschaben** [comment]
is this still an issue to be addressed? If not, please close, thx.

**Comment by jrjohnson** [comment]
Yes, we still have this problem.

**Comment by stopfstedt** [comment]
so i did some work on this in a feature branch, and i really don't like how this turned out. could be my sub-par implementation, but i think there's also some conceptual flaws.
for one, we're trying to make a sub-state of a sub-state stick around, whereas it's parent state ("editing objectives") is implied/can only be set by interacting with the page. which leads to all kinds of additional state checking/hole-punching in order to get us there.
the end result seems rather complex and brittle. 
IMHO, this warrants revisiting the issue whether this is desirable after all.

**Comment by stopfstedt** [comment]
@jrjohnson @saschaben thoughts?

**Comment by saschaben** [comment]
Let's use Tuesday meeting time to discuss issue & options

**Comment by stopfstedt** [comment]
this got discussed and rejected.
