### ISSUE TITLE
Can we use the objective manager slide in other places?

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#259]
I'm specifically thinking about topics and mesh terms on a course or session.  It would solve our save / loading issue if we displayed the topics and had a button to edit.  When editing was selected the current add / delete interface would slide in and changed could be made.  When they were done they can save or they can undo.

Thoughts?

**Comment by saschaben** [comment]
Hmm. Possibly.

This puts some pretty heavy process on the user for what is otherwise a very lightweight action; I can envision it (sorta) but I'd need to see mockups. Also, I'm not sure I'm seeing how this affects the save issue exactly, since we will have multiple selects in almost every instance in each of these cases (topics and mesh), but show me an example and we can discuss.

Remember that there is a real difference between adding a tag or badge (as we do in topic and mesh) and creating a linked relationship (as we do with objectives).

**Comment by jrjohnson** [comment]
I'm thinking this is actually a way to get to the future phase mocks: https://www.dropbox.com/s/6qbzgs0tow9t1pu/Course-Detail-Page-v5-SemiCollapsed.png?dl=0

It would be like a collapsed state for topics and mesh.  Then when you 'un-collapse' you would actually open the editor to make changes.  

The difference in saving behavior that we might want to bring to the objective inspector is we would  not persist each change as you made it, we would only save when the user hits done.  This would give us the ability to encapsulate the whole thing and prevent the re-rendering that is causing problems now.  It would also let us add some fun stuff in the future like undo.  

The reason I bring this up for 0.2.0 is because if we are moving from live edit or relationships to save when done editing then that is something we have to decide now.  I'm honestly not sure if the is a step back or forward.

**Comment by saschaben** [comment]
ahh. I get it. and then we'd be saving an array all in one fell swoop (sort of like being in our current dirty state)

I'm also not sure which route here is smartest. It would be helpful if we had a clickthru for each pathway on this to play with and discuss future options.

**Comment by saschaben** [comment]
I guess the major question is what is the impact on the user of the "done" button vs the instant save action. Some of that is code related, and some of it is way more human factors stuff. This is a conversation that needs to be had with all hands, @jrjohnson @jenzweben @thecoolestguy and @dartajax to represent the valentinas.

**Comment by jrjohnson** [comment]
@saschaben - here is what I'm thinking.  We would need to handle errors correctly, but the save is sort of transparent.  We would FOR SURE need an indication that the topics are dirty while managing.  Probably just changing 'Done' to 'Save' might do that.  This cleans up the UX a lot though - so as long as we can be ok with - and correctly indicate - dirty state in the manage box then I like it.
![manage_topics_demo](https://cloud.githubusercontent.com/assets/349624/6493620/b45815ba-c270-11e4-953e-a7c7cdada802.gif)

**Comment by saschaben** [comment]
What if instead of "done" button" we use the same control set as we do for inline edits - green check and undo? That way the user has consistency across control entities despite their working differently behind the scenes, and provides (I hope) the necessary cue that SOME action needs to be taken after the change.

**Comment by dartajax** [comment]
That is a nice animation.  I like the circle that pops up when editing.

**Comment by saschaben** [comment]
We will move forward with this pattern as our basic one for these situations: and will apply the inline edit controls in button format for save and cancel.

**Comment by thecoolestguy** [comment]
For the confirmation/undo buttons at the upper right, we're going to use color 'white' for the the text and the red and green colors as the background (as seen in the check-in meeting!)
