### ISSUE TITLE
More Information Needed in MyReports >> Course Drop-Down

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2837]
As shown below, in MyReports, if a Course has the same name year over year without specifically putting in the year, it becomes impossible to know which one is being selected for the report.

![image](https://cloud.githubusercontent.com/assets/7493331/24632745/2b97515c-187a-11e7-9da3-e419c0ec9377.png)

**Comment by saschaben** [comment]
This is equally true for the session dropdown.

Courses should include `external_id` and (if possible & easy) academic year along with title in the dropdown selector.

Sessions should include (if possible) course title.

**Comment by djvoa12** [comment]
Current changes reflected in the screen shots below. Waiting for Sascha to sign off or comment for further changes.

<img width="856" alt="Screen Shot 2019-04-22 at 1 36 59 PM" src="https://user-images.githubusercontent.com/7553764/56518462-24506080-6505-11e9-86ce-2fcce994be0f.png">

<img width="854" alt="Screen Shot 2019-04-22 at 1 37 24 PM" src="https://user-images.githubusercontent.com/7553764/56518463-24506080-6505-11e9-88b5-2f618decc51f.png">

**Comment by saschaben** [comment]
notes in this comment stop stand: 

https://github.com/ilios/frontend/issues/2837#issuecomment-387562496

for COURSE listing, we should present

`year | [external_id] | course_title`

for SESSION listing, we should present

`year | session_title | course_title`

since external ID isn't required, we need to check for existence. I'd prefer to use it as the identifier for session as well, but again... not required so we will need the course title.

**Comment by saschaben** [comment]
sort order should be: `order by year, title`.
