### ISSUE TITLE
Cohorts Are Missing from Calendar Filters - Matriculation Years Only are Showing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2909]
All Program Years that are currently active should be displayed in the filters on the Dashboard Calendar.

![image](https://cloud.githubusercontent.com/assets/7493331/25410059/93c9faee-29c9-11e7-8520-e5e3da622888.png)

This shows only the ones that started in 2016-17 - I have no idea about higgly.

It should show the other active program years like class of 2019 SOM and class of 2018 SOM as well.

Loading up the previous year, just the ones that started in 15-16 are displayed.

![image](https://cloud.githubusercontent.com/assets/7493331/25410114/d0db7d5e-29c9-11e7-8884-98217262bfb9.png)

If a program starts in 2015-16 and is 4 years in duration, it should show up in the drop-down until 2019-2020.

**Comment by jrjohnson** [comment]
@saschaben I don't know if this should be categorized as a bug that needs to be marked ready and fixed immediately or as an enhancement that can be backlogged.  Can you take a look and make that decision?

**Comment by saschaben** [comment]
Good question. On the one hand --- bigger fish to fry. On the other --- this makes the filter frustratingly difficult for faculty to use, and this is, for a large population, the *primary* use case for their filter interaction ("show me the entire schedule for the 2nd year students"). It is definitely a bug, not an enhancement, since the current functionality is just plain wrong. Let's discuss at codejam?

**Comment by saschaben** [comment]
i think we need to put this in the ready queue -- the fix should be pretty simple (add the calculation of current selected year > cohort matriculation year > duration of program) if we already have the full data in the current call...
