### ISSUE TITLE
Course & Session Detail Header Clean Up / New Publish Buttons

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#291]
Here are all the states (and I added styling annotations too)  Sascha - if you approve, please assign to JJ.  I'm recommending styling the background color on hover of menu items that are either "dangerous" or desired.  Blue bg is neutral...

![publish-button-options](https://cloud.githubusercontent.com/assets/5023894/6563966/5f1e7904-c662-11e4-907d-08035db81d19.png)

**Comment by saschaben** [comment]
Looks good. We might want to consider a different color for  "not published" -- red is danger, and this is just the unfinished state -- otherwise let's roll with it. I do like the bg color on hover idea very much.

@jrjohnson please note that despite the variety pack this is  _not_ all states when it comes to dropdown list values (fer instance, scheduled requires an unpublish), but we can review that as you concatenate the existing controls.

**Comment by jenzweben** [comment]
Here's another mock showing Session Details page header
![screen shot 2015-03-09 at 3 16 07 pm](https://cloud.githubusercontent.com/assets/5023894/6565706/5d6c214e-c66f-11e4-883f-2a95906aafc4.png)

**Comment by jenzweben** [comment]
Here's the Session Detail Page header mockup 
![screen shot 2015-03-09 at 3 19 09 pm](https://cloud.githubusercontent.com/assets/5023894/6565753/b3acff56-c66f-11e4-9a0f-9cd450570e17.png)

**Comment by saschaben** [comment]
per @jenzweben please note that we now have the possibility of confusion: session badge and course badge being identical yet pertaining to different stuff.

perhaps just address this in the dropdown fields? schedule COURSE, publish COURSE as-is, unPublish SESSION, etc....?
