### ISSUE TITLE
modify sync window

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3042]
move to 3 back 3 forward, instead of 4 back 2 forward

**Comment by saschaben** [comment]
it may be time to look at making this a configurable issue for schools....

**Comment by jrjohnson** [comment]
The problem is that the user is the driving force for the sync. Do we make it obey the configuration of their primary school? Or should we allow users to customize their own window?
The best experience *may* be to just let the user pick and warn them that if they set the window too large it may not work. We could do a test run that pulled the file to get its size and then warned the user that they had gone over where we think the soft limit is for google.

**Comment by saschaben** [comment]
Interesting. We *know* the google limit is 1.1MB; we also know that in practice more than 6 months of a standard med student schedule busts that limit. Lot of ways to skin this furred purring housepet.

**Comment by dartajax** [comment]
we have other tickets to address this
