### ISSUE TITLE
Add Hairline Border to Calendar Filter Badges

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3092]
It would be easier to see the badges if there was a border around them.

Yes, the border should be slightly rounded to match the other one.

![image](https://user-images.githubusercontent.com/7493331/28143994-d0341b22-671d-11e7-926e-bb35fde478a1.png)

**Comment by mhgh22** [comment]
Filters are visible/highlighted in different shades of blue without borders based on the section selected. When numerous filters are selected, the blue shades appear to blend in and bunch together with no/uneven spacing. -Michael/Nanci/Stacey @dartajax

![i3092](https://user-images.githubusercontent.com/103135575/162286406-9b2c3f74-b9f4-4dc7-9dca-15f599f44f63.png)

**Comment by dartajax** [comment]
Thank you all for checking this out. My original ticket was entered because some of them used to have white background which matched the background. I am going to leave this open for now but may create a new ticket to have more color differentiation in the blue - maybe have green for the third column or something - Ilios orange maybe.

**Comment by stopfstedt** [comment]
i think we're arguing the wrong solution here with color coding. it creates problems for visually impaired users, and does not provide any context to their category at the moment ("what category is dark-blue again?").

instead, active filters should be grouped by their filter category and prefixed with that category's name as label.

this will may take up more space in the UI (one line per category with active filters instead of one line for all active filters), but it's the cleaner, more accessible, and more informational display.

**Comment by mhgh22** [comment]
when i was looking at this issue, i too thought about grouping filters together by their category with the filter's name/heading above the list/column or in front of row. this way, the different filters are separate and cleaner to look at, and possibly remove the need for color. but like stefan said, will take up a bit more space in the UI depending on which format is used.
