### ISSUE TITLE
Start week at a glance on Sunday

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#3135]
User feedback is pretty strong that weeks should start on Sunday instead of Monday.

**Comment by saschaben** [comment]
The challenges we are looking at: pre-work is assigned to students on the weekends -- so we need to provide them with some continuity of information frmo end of one week to start of the next. Starting on Sunday is a start: helping the navigation to the "all weeks"" view to allow them to see last week/next week together; longer term we should re-introduce the possiibility of making this a scrolling window, rather than locked to a single week; also longer term the ability to configure school and personal preferences for display.

This is all roadmap stuff -- not actually to be DONE in this ticket, but to provide context for the first steps to be done in this ticket.

**Comment by saschaben** [comment]
updated language for the all weeks link:

![newlabel](https://user-images.githubusercontent.com/1753431/29185322-b6e56246-7dbd-11e7-98fb-21d0b982f4f1.png)

FR: `Vue: dernière semaine / la semaine prochaîne / toutes les semaine`

**Comment by dartajax** [comment]
ES: ```Vista: La Semana Pasada / La Semana Próxima / Todas Las Semanas```

**Comment by saschaben** [comment]
Fixed with https://github.com/ilios/common/pull/16
