### ISSUE TITLE
Course/session "missing items for review" is counting wrong

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#318]
the count being displayed for missing items for review in the publish selection list is wrong: instead of _n_ = _n_(d) where  _n_ is the number of missing items and _n_(d) is the displayed number, we are getting _n_ = _n_(d) + 1

**Comment by jrjohnson** [comment]
Can you give me some specific example?.  I'm seeing the correct number in the cases I checked.

**Comment by saschaben** [comment]
huh. this now appears to be counting right. It was really broken -- really! I even showed it to Dave. This may have cleared itself up with the last batch of merges.....?

**Comment by dartajax** [comment]
The screen shot below is at the Course level indicating there was one item missing (topics may be problematic).

![publishcourse](https://cloud.githubusercontent.com/assets/7493331/6930761/fb88f896-d7ba-11e4-8e11-e1f00fbdb8d7.JPG)

The next screen shot shows that all items have been entered correctly and the count is working correctly here but not at the course level.

![rvwmissing](https://cloud.githubusercontent.com/assets/7493331/6930763/fe49bd9a-d7ba-11e4-814c-85ef40b7c976.JPG)

**Comment by jrjohnson** [comment]
@saschaben / @dartajax - you mentioned in our meeting that you had steps to reproduce, can you include those here?

**Comment by dartajax** [comment]
* So pull up Prologue and add a new session.
* Select Review 4 Missing Items and notice that there are 4 items 
* Return to the Session 
* Add an Objective to the Session 
* Select Review 3 Missing Items and notice that there are 3 items 
* Return to the Session 
* Add a Topic 
* Select Review 3 Missing Items (this should have been two since the topic was added in the step below)
* Notice that it claims there are 3 Missing items and that Topics is still missing 
* Return to the Session 
* Scroll and ensure that the Topic was indeed entered and saved -- it was
