### ISSUE TITLE
Blank Spaces Only Should Not Satisfy the 3 Character Data Entry Requirement

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3377]
We will be trimming these on the way to the database anyway.

Refer to #3369 

However, currently it is possible to enter three blank spaces to satisfy the 3 character minimum for data entry. The Save event frequently has problems with this. And in other situations, it becomes impossible to edit or delete something that was successfully entered with all blanks as the text value.

Here is a list of fields that should be modified to not allow this to occur ... thus preventing other problems.

Courses and Sessions >> Course Title
Courses and Sessions >> Course Learning Material >> Display Name
Courses and Sessions >> Course Learning Material >> Content Author
Courses and Sessions >> Course Learning Material >> Copyright Rationale
Learner Groups >> Learner Group Title
Learner Groups >> Default Location
Instructor Groups >> Instructor Group (on Update only)
Schools >> School Title
Programs >> Program Title

**Comment by stopfstedt** [comment]
some thoughts and opinions on this...

first off, the validation library that we're using, ember-cp-validations, does not provide this out of the box. 

however, we could roll our own custom validator that checks if a given string has whitespace at the beginning or end of it. 

or, we could also contribute this as a config option for existing validators to the project.

the third option that comes to mind would be to prevent users from entering whitespace on the boundaries. this is my least favourite one, since we'd also have to deal with copy/paste and could make for a confusing user experience ("i press spacebar and nothing happens").

**Comment by jrjohnson** [comment]
We've handling this in our octane validators, fixes will trickle out to components as they get updated.
