### ISSUE TITLE
Courses and Sessions >> Learning Materials >> Can Author / Owner Be Modified?

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#388]
I was realizing / hoping that these fields could now be edited by the user since we are now allowing other edits to occur.  Can we allow editing of these / all fields?

**Comment by saschaben** [comment]
This is a bigger than a breadbox issue: if you take ownership of a file, you may be messing with intellectual property, faculty egos, or other large issues. Since  a file can be used by multiple people in multiple places, it can get sticky if ownership is not locked down.

Since we no longer lock the status changes to the owner, I think we can leave this as is for now.
