### ISSUE TITLE
Cohorts & Topics

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#394]
These sections should not have the check & undo buttons, they should have a close button like we are using for Directors

Like this: 
![screen shot 2015-03-30 at 12 25 50 pm](https://cloud.githubusercontent.com/assets/5023894/6904756/0817d322-d6d8-11e4-8b31-73d266b6989d.png)

NOT this:
![screen shot 2015-03-30 at 12 24 02 pm](https://cloud.githubusercontent.com/assets/5023894/6904760/10c459fa-d6d8-11e4-957b-6a354f3b2f29.png)

**Comment by saschaben** [comment]
This is actually a technical requirement that we put in to alleviate a functional problem with these panels: we have had to introduce a "dirty state" in order to save properly without disrupting the user experience by jittery weirdness, so we need a "save" and a "cancel" value here, not just a "close". This was discussed in monday meeting two weeks ago.

Regardless, we HAVE to re-align the damned buttons.

**Comment by jenzweben** [comment]
OK got it but the buttons should be directly to the right of the selection box rather than super far away in the right column...

**Comment by jrjohnson** [comment]
We're using the same manager pattern for all of these field types.  In each case the Save / Cancel buttons are over on the right.  In the cases where we don't have it like directors and mesh we were planning to add it.

Should we move all of those buttons?  Can we see some mocks for this and talk about why they need to be close to the box as opposed to on the right where all the other action buttons are?

**Comment by jenzweben** [comment]
Usability testing has proved this issue moot.
