### ISSUE TITLE
Courses List Page Filter Tools Style & Content

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#398]
I thought that we were going to move the School to the title bar (where it currently says "Courses") and that we were going to label the year dropdown with "Academic Year"... 

At any rate, we need to clean up the styling & alignment of the filter tools...Here's the mock for Single School

![course-list-oneschool-v2](https://cloud.githubusercontent.com/assets/5023894/6906174/ecb750f8-d6e1-11e4-816d-6c0f06cf1c0f.png)

**Comment by saschaben** [comment]
I believe we left school as it is now due to dealing with multiple school selection: when we implement it, we'll need monkey buttons or the equivalent, and that won't work in the header. This leaves us with limited space for an "Academic Year" label -- I think we need to see how the users respond without it, before we reconfigure the whole filter header to accommodate it. Does that make sense?

**Comment by jenzweben** [comment]
yes it does - the existing tools still need some styling help...it looks like the dropdown and the filter box are different heights and it would probably look better if we decrease the space between the Toggle, School Label & Year dropdown and left justify the filter box...

**Comment by saschaben** [comment]
closed
