### ISSUE TITLE
Show Explicitly Labelled Buttons Instead of Generic

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#420]
From user feedback, we want to avoid having buttons that just say "Add" or "Update".  We want to have the exact item to be added or modified to be appended to the button caption for more clarity.

**Comment by jrjohnson** [comment]
I'm not convinced this is a good path.  It will make all of the buttons different sizes which may cause alignment issues on the page.  Additionally it will require adding a lot of new translations which we then have to manage.  From my perspective having the same size / text 'Add' in every section actually makes the app easier to use because you always know to look in that corner and click that button.

Can we bump this until we get more user testing done and then decide if it is necessary or just something that came up in testing because of unfamiliarity with the interface?
cc/ @jenzweben @saschaben

**Comment by saschaben** [comment]
Bump it. I think that this is one where the users aren't going to get what they want. They will get what they need.

Buttons with text will be specific to function, but not to functional area: so "Add" "update" etc. HOWEVER: we should look to making certain that wherever we use text buttons it is explicit as to what the actual function and outcome will be for the user. AND we should continue to consider replacing text buttons wherever possible with icons.
