### ISSUE TITLE
Prefix ILM Session Type in WaaG if Other than "Independent Learning"

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4317]
If a linked ILM Session has a session type other than "Independent Learning", this session type value should be pre-pended to the PreWork ILM (the first part) so ...

(Movie) Biochemical Contributors to Anion Gap Acidoses 

_instead of_ ...

Biochemical Contributors to Anion Gap Acidoses

Putting "Independent Learning" at the beginning would be redundant since ...
* The Session was already flagged as ILM
* "Independent Learning" tends to be the default and offers no extra information.

However something like a session type of "Deadline" or (as in the example) "Movie" would prove to add value to the user.

**Comment by dartajax** [comment]
This is in Week at a Glance (WaaG)

**Comment by jrjohnson** [comment]
This is actually difficult bordering on impossible. The issue is that the session type title is a database field that can be edited for any school and could br written in any language. Without a consistent string to compare it to I’m not sure how to not write the session type when it is `Independent Learning`.

I can *always* put in the type. But it’s impossible to *sometimes* put in the type.

**Comment by saschaben** [comment]
obsolete
