### ISSUE TITLE
Remove Spacing Around LM Description (Above and Below)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4360]
Here is how it is currently ...

![image](https://user-images.githubusercontent.com/7493331/53275013-53d22080-36ae-11e9-8c4f-2a12d7cdf8ac.png)

Here is how it is currently with blue rectangles around each LM ...

![image](https://user-images.githubusercontent.com/7493331/53275028-5df41f00-36ae-11e9-946d-222c93cf2b4b.png)

Fixed up, it might look something like ...

![image](https://user-images.githubusercontent.com/7493331/53275365-acee8400-36af-11e9-8647-c6ed40f04f25.png)

**Comment by stopfstedt** [comment]
it's the LM description - the wysiwyg editor wraps any given content in paragraph tags.

**Comment by dartajax** [comment]
Then it should wrap the instructional notes in <P> tags too? or why when there are instructional notes and description does it not add the extra spaces?

**Comment by saschaben** [comment]
I believe the issue is the variability display option for instructional notes: since they may be set to "hidden" or "displayed" for this student view, my guess is that the grid currently creates a space for them, regardless of their visibility option selected. So when hidden, there is just the placeholder space; and when they are displayed, the problem goes away.... @stopfstedt can you verify?

**Comment by stopfstedt** [comment]
> I believe the issue is the variability display option for instructional notes: since they may be set to "hidden" or "displayed" for this student view, my guess is that the grid currently creates a space for them, regardless of their visibility option selected. So when hidden, there is just the placeholder space; and when they are displayed, the problem goes away.... @stopfstedt can you verify?

not the case. if the instructional notes are turned off for public display, no placeholder gets rendered. 

the real issue here is how the LM description and the LM instructional notes are styled differently. 

also, in the example above, it appears that the description on the last LM made it into the system without being wrapped in a `<p>` tag - the UI enforces that, but perhaps this one came in via direct DB manipulations or the API, adding to the confusion.
