### ISSUE TITLE
Offering manager requires styling

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#452]
A follow-on for #387. 90% should be handled with the application of the generic form.

Additional issues of note:

* action control dropdown is currently hidden when offering is less than three lines tall;
* offering requires "delete" function
* Group selection is sorting by last item in name list; should sort by full title in order to represent parent and child groups correctly;
* on save, requires slide transition back to normal display.

**Comment by saschaben** [comment]
assigning to @thecoolestguy for inital form implementation; Jason when you've got this covered please hand off to @jrjohnson if need be to address additional issues.

**Comment by dartajax** [comment]
One more thing I noticed regarding the action control dropdowns -- they do not appear at all even when there is room as shown below.
![nodropdown](https://cloud.githubusercontent.com/assets/7493331/7329823/12e14426-ea99-11e4-8283-91b1066a25ec.JPG)

**Comment by saschaben** [comment]
@dartajax I think there is already a ticket for this --- maybe we only talked about it --- the drop down can only be seen when more than one row of text info is given for an offering, like multiple instructors, or groups, or locations.

**Comment by saschaben** [comment]
actually, duh to me: see first bullet in my first comment "addiitonal issues of note".

**Comment by dartajax** [comment]
Yeah I was adding on to that bullet point - since I noticed the cut offs as you did.  But then I noticed - well you can see my comment above your last one -- Plenty of room on the that top one with nothing displaying.  My guess is that it is due to the add people icons showing.  We need headers on this one too but I bet that is another ticket.

**Comment by saschaben** [comment]
there has to be actual text data (additional names, rooms or groups) in the avaiable row space, otherwise it still gets hidden.

**Comment by dartajax** [comment]
OK.  I hear you.  In my example with the new straight red ("Plenty of room to show") arrow, nothing gets displayed at all even though there is room.  I can show you on Monday or you may already know the reason for this though.

**Comment by dartajax** [comment]
![triestofindroom](https://cloud.githubusercontent.com/assets/7493331/7330248/a12ba072-ea9f-11e4-8971-bda24fdc77ed.JPG)
![doesnteventry](https://cloud.githubusercontent.com/assets/7493331/7330249/a40da308-ea9f-11e4-84a1-161b10093ac5.JPG)

**Comment by saschaben** [comment]
a minimum of three lines of text:

![ilios 2015-04-24 16-51-25](https://cloud.githubusercontent.com/assets/1753431/7330366/3eca8a4e-eaa2-11e4-8e79-3fccecffd63b.png)

**Comment by dartajax** [comment]
OK.  So the ones where I was claiming above that it doesn't even try is because there are zero lines of text and it requires at least three for the items to display.  OK - we need to fix it either way but it may just be one fix at least.  I thought I saw something weird but it's just the same thing.

**Comment by jrjohnson** [comment]
More styling notes in duplicate ticket #390

**Comment by jrjohnson** [comment]
New individual issues opened in 
#622 #621 #620
