### ISSUE TITLE
Create Programs Landing Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#462]
![programs](https://cloud.githubusercontent.com/assets/5023894/7238611/6a0fba6e-e758-11e4-824a-813e8abdd117.png)

**Comment by saschaben** [comment]
good to go. Do we want to add action controls to this list? Just an open question....

**Comment by jrjohnson** [comment]
@jenzweben / @saschaben Couple of questions -
Can more than one school be selected at once?  If No is there an significant reason to use this interface instead of a drop down which is much easier to implement? If Yes - why?

I think the search box should actually save 'Filter by title' to be consistent with the courses list.

On the courses list the header-bar says 'Courses', here it says 'School of Medicine' which represents the filter selected.  Which one of those is the correct use of this element?

**Comment by jenzweben** [comment]
If the user has access to only one school then the header bar would say Programs.  Mock is showing monkey buttons per long ago request from Sascha to show what they would look like.  My understanding is that a user may only select one school at a time but @saschaben please confirm

**Comment by saschaben** [comment]
@jrjohnson @jenzweben correct: One school at a time. Please proceed.
