### ISSUE TITLE
Return to the Same Session In Session List After Expand or Contract All

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4820]
Steps ....

* Navigate way down on a course session list ...
![image](https://user-images.githubusercontent.com/7493331/64656279-cce35c00-d3e3-11e9-91a2-b57514690cb7.png)

* You end up landing where the Session Titles start closer to the beginning of the alphabet but in any case, it will require scrolling to return to the previous location.
![image](https://user-images.githubusercontent.com/7493331/64656391-23e93100-d3e4-11e9-8022-a1626b303875.png)

**Comment by dartajax** [comment]
another totally reasonable issue

**Comment by stopfstedt** [comment]
> another totally reasonable issue

impossible to do. since the session list expands, the calculated scroll point is always wrong as the list is still collapsed when the window's view port coordinates are captured. in other words, the scroll will always come up way short since we'll be using coordinates that were calculated on the collapsed view.

**Comment by jrjohnson** [comment]
Instead of coordinates I wonder if we could scroll to the session by ID? So as IDs scroll into view we could record the id of the top one and then after expanding go to that point?
