### ISSUE TITLE
Add vocabulary terms tagging to Objectives

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#4863]
To address the needs of Pharmacy School mapping / accreditation needs, we will add the ability to tag objectives with vocabulary terms. This requires a bunch of things:

- [ ] addition of x-ref table(s) in the schema
- [ ] addition of new display column in Course Objective Details
- [ ] addition of new relationship to MyReports reporting syntax where Terms are invoked
- [ ] addition of new relationship for tag association / count in vocab management
- [ ] addition of listings for "terms associated by objective" to course visualizations where appropriate
- [ ] ???

Questions to be answered: 

- is this provided at all levels (Program/Course/Session), or only course?
- should this be a school-level configuration ("pick MeSH - Vocab Terms - Both"), or standardized into the platform?

**Comment by stopfstedt** [comment]
yes on all levels, unless there's a compelling reason not to do so. it would be harder to suppress this at certain objective levels than allowing it everywhere.

re: configurable at the school level vs instance-wide - i'd go with the latter. again, easier to implement, and schools that don't want it don't have to use it.

**Comment by stopfstedt** [comment]
_per team convo today:_

vocabulary terms should be associated with objectives at the session/course/programyear-objective level, not directly at the objective level. 
this will require a more substantial re-write in order to expand session/course/programyear-objectives from cross joins to first-class data points in our model.
