### ISSUE TITLE
Indication of newly added Data (helpful for user)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#569]
Mock needed for this one.

It would be helpful to have an indication (possibly by shading or a different coloring) when a new entry has been made (new Topic added, new MeSH added) so the user can review what was just entered vs. pre-existing data.

Initially, I had thought that this could be used when a new Session or Course is added; but in those cases, the user is taken immediately to add details.  Topics is a good example to work with I think.

I hope this makes sense.

**Comment by saschaben** [comment]
While I am on board with this idea, I'm concerned about using color or styling alone to present meaning -- it's dreadfully un-accessible. @jenzweben I'll leave it to you to come up with some options here to consider, but @dartajax is right, topics is a good example to start with.

**Comment by jrjohnson** [comment]
When does this indication appear?  During the editing phase when the manager is still open?  Or after the changes have been saved?

**Comment by saschaben** [comment]
@jrjohnson I think it would have to be after save; there are some pretty solid reasons why we've never implemented before/after comparative data onscreen till now: it's really complex to make it truly valuable to the users without being burdensome. How long does the indicator last? Who sees it? can it be brought back for view as an auditable entity? How is it made accessible? Where does it or does it not come into play/display?

I'd like to put this into the "future things" bucket for now, and just get some ideas in play. It will help stimulate our appetites.

**Comment by jrjohnson** [comment]
If we make it:
1. After Save
2. Expire after a certain time (or when the user leaves the page)
3. Not undo-able
4. Only for the user who made the change

This is a pretty easy thing to do.  We would just keep a list or before in memory and then after a save for a certain amount of time we would highlight the differences.  It probably more work to do it 30 times (on every place it would make sense), but not a huge deal.

**Comment by jenzweben** [comment]
Here's what I was thinking - after the user saves, we highlight the item in success green bg (I will mock) and it fades out...

**Comment by saschaben** [comment]
@jenzweben I think that is more effective for a solution to #570; @dartajax can correct me if I'm wrong, but I think this one is more about the user's ability to audit (or self-audit) changes made in order to allow for a CYA review period and potential correction. So any indicator would need to have a little more staying power -- along the lines suggested by @jrjohnson above.

**Comment by jenzweben** [comment]
Hmm I feel like this might be overkill...

**Comment by saschaben** [comment]
@jenzweben it is overkill. Absolutely. But the underlying user request or need is worth us discussing, as it has been flung around for a decade here. This might not be the solution at all, but we should talk about why there is a question to begin with, and tease out the ways we can perhaps make it Just. Go. Away.

**Comment by jenzweben** [comment]
OK what is the problem we're trying to solve?  Is it that users forget the orginal value (content) that they replaced?

**Comment by saschaben** [comment]
@jenzweben That's one. the other is a level of trust that what they selected/replaced is what is now being shown to them correctly; the other is just validation that they've actually done the right thing by visually confirming.

A place where this frequently has come up over the years is in the replacement of instructors: Jane is scheduled to give the Anatomy lecture, but at the last minute has a conflict and gets replaced by Joe. The evaluations teams and other administrators, in order to send out the proper forms to the right people and to give teaching credit to the right person need to know not only who IS teaching, but who isn't. This is  a MUCH larger issue (i.e. audit trail analytics and alerts) than just on screen indicators.

In this particular case, coming from Dentistry, we already know that there is a real lack of trust in the system to function as expected, so it's no surprise that the current emphasis is on a visual indication to verify that what I have removed is actually gone, and what I've added has actually been added.
