### ISSUE TITLE
Admin Calendar View of User's Events - Events Should Be Disabled or Allow Access to View

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5813]
Below is a screen shot from the Admin Console. The user 17223 is not the user who is logged in. The logged in admin user is not directly associated with the Calendar Events and when the logged in admin user clicks on any of the events displayed, they will receive the coveted "Rats ..." error. It would be best if the admin user could see and view the Event Details screen in order to research the user's calendar if that was the intent. If this is not possible or is considered to be giving too much information to the admin user (only limited people should have this advanced level of permission), we can disable the clickable characteristics of these calendar events inside the Admin Console.

![image](https://user-images.githubusercontent.com/7493331/105406919-edc7de00-5be1-11eb-8c8f-2cb8f815f25a.png)

![image](https://user-images.githubusercontent.com/7493331/105406967-fb7d6380-5be1-11eb-9634-d337bad0d244.png)

**Comment by stopfstedt** [comment]
refs https://github.com/ilios/frontend/issues/5548

**Comment by stopfstedt** [comment]
unlike school events, the user context is missing from the user event slug. currently, that context is provided by implicitly assuming the user events are requested for the current user. 

changing this would require encoding the user id in the slug. which would be a breaking change, all links to user event details currently out in the wild would break.

if that is acceptable then i could attempt to correct this issue.

otherwise, our only option would be to roll back the user-event click-through in the user admin calendar.

@saschaben and @jrjohnson, please advise.

**Comment by jrjohnson** [comment]
I wonder how difficult it would be to translate a user event into a school event. Some kind of method on the CalendarEvent on the frontend? Then clicking on an event in the user profile page when you are not the user could take you to the school event directly.
