### ISSUE TITLE
Make Adding Learning Materials a One Step Process

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#586]
It would be helpful if all of the fields for adding Learning Materials to any applicable curricular object were available initially - making the addition of Learning Materials a one step process.

It depends of what type of Learning Material is being added of course.

The additional fields in any case, which currently have to be added in a second step once the initial upload has been completed, are ...

* Required 
* Show Notes To Students 
* Notes (the text of the notes)
* MeSH terms pertaining to the LM

**Comment by jrjohnson** [comment]
@jenzweben / @saschaben any reason we have this broken up currently?

Mesh Terms needs to be handled separately - it requires a save first I think to work right.  Setting the meta-data for notes / required is technically easy to do on the initial add form.

**Comment by jenzweben** [comment]
My recollection is that Sascha had a specific reason for wanting a two-step process...something to do with what it is that a user is actually "noting"...

**Comment by saschaben** [comment]
The reason for two-step:

learning materials are first added to the repository of files, with their basic file metadata. that's step one.

learning materials are next selected from the repository and attached to a given session or course, along with the metadata and notes specific to that particular use of the file in that particular course or session. that's step two.

for users, the process goes pretty much like: 
A: I need to add XXX to my session. I think it's already been used before, so I search the repository for it.
B1: 
 step 1: I find it, and select it for my session, 
 step 2: adding learner notes and setting it as a required text.
or
B2: I don't find it, so 
 step 1: I upload it to the repository, and then 
 step 2: associate it to my session, adding my specific notes and setting it as required.

Since the patterns are variable in their relationship, and because the details in step 2 are unique per use, while the details in step B1 are permanent, and in A1 are simply a search, it really forces the need for a two step process here.

**Comment by jrjohnson** [comment]
I'm not sure I understand your explanation.  Here is what I'm thinking are the two scenarios.

1) A user finds the file they want to add, adds it, then sets the session data (showNotes),

2) A user doesn't find their file.  So they create a new one, fill in all fields, pick session data (showNotes), then clicks save.  We know on our end that they have both created a new learning material and associated that material to their session with extra data, but they don't need to know that.

Since there is no case where a use adds a new file and then doesn't associate it with the session they are working in we don't need to force a two step add process.

**Comment by saschaben** [comment]
if we make it a one step process, how do we provide the user with the context of understanding that the information in step two is not a part of the file information in step one?

**Comment by jrjohnson** [comment]
I'm sure we can come up with a visual solution for this.  But my first question is why do they need to understand that?  I'm thinking it is so they aren't worried that their notes and required selections will carry over into other uses of the file?  Maybe we could draw a line and say something like - *These options will apply only to the BMB Small Group Session*

**Comment by saschaben** [comment]
Doing something similar to that was roundly rejected by the users in the earlier version: responses were along the lines of "every time I tried to use my slides, the notes would disappear and I've have to add them again, it's broken! It keeps reverting from being required, it's broken!"

Users aren't rational. Keep that in mind. If you give them the option of adding metadata for a file relationship in the same context as adding metadata for a file, they won't pay attention much to any distinction you make between the two. They should have to pay that much attention to understand it.

Unless @jenzweben can come up with something that makes it patently clear via process (not thru labels) for the user to really understand that they are doing two entirely different things here, I don't see us combining the two at this time.

**Comment by saschaben** [comment]
Also, let's keep in mind that it's only UPLOAD / attach that is a two step process: SEARCH / attach is pretty much one step.
