### ISSUE TITLE
Implement Bulk Editing for Learner Groups

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#612]
Per our discussion at the team meeting on May 21, in order to allow users to edit groups & subgroups when they are dealing with a large number of people, we're going to try adding "Bulk Edit" functionality.

**If anyone can think of a better name for "Bulk Edit", speak up!**

We need to make sure that when Bulk Edit is on, that the list of members NOT in this group become read-only (or we need to discuss the best solution)...

Bulk Edit = on

![learner-groups-edit-v10-bulkedit](https://cloud.githubusercontent.com/assets/5023894/7759774/41f3b5d8-ffc9-11e4-8eb5-7001445832ed.png)

Default State (Bulk Edit = off)
![learner-groups-edit-v10-default](https://cloud.githubusercontent.com/assets/5023894/7759696/7cd37f40-ffc8-11e4-83d3-6b16363edf0f.png)

**Comment by justinchu17** [comment]
What about 'Multi-Edit' instead of 'Bulk Edit'?

**Comment by saschaben** [comment]
@justinchu17 has a good point: we aren't really "bulk editing" here: we are assigning multiple people to their appropriate places. @dartajax it might be good for you to present what we are trying to accomplish here to valentina and see if she has an opinion on nomenclature.

**Comment by jrjohnson** [comment]
Few things:
1) Slider for multi-edit/single-edit instead of on / off with a label would match what we are doing other places.
2) Same for entire cohort slider.
3) When multi-edit is on can we hide the bottom sections as well.  Otherwise its going to get to be a bit of  a mess of who goes where when someone changes a single person at the bottom of the page while multi-edit is engaged.
4)This is VERY cool @jenzweben you took what we talked about abstractly and made it into something very concrete and interesting.  Nice work.

**Comment by dartajax** [comment]
A quick question ... after the user selects a bunch of folks and clicks the green save button, what happens?  I am assuming the screen would refresh and all of the newly added people would then appear up at the top.  Or when the user selects them one by one, do they move immediately to the top?  By the top, I am just referring to the upper part of the screen where Andrew Woods currently is.

This looks really nice and I will ask Valentina to come take a look at it.

**Comment by jenzweben** [comment]
You are correct.
