### ISSUE TITLE
Add Course Rollover function

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#686]
A course may be rolled over into any educational (academic) year that includes dates after its start date. It may be rolled over with or without calendared events (offerings).

**Comment by thecoolestguy** [comment]
So, here are the afftected database tables and the base SQL queries used when rolling over a course and its associated sessions, offerings, instructors, instructor groups, objectives, and learning materials.

Learners and Learner Groups are NOT included in a rollover, because they would need to be manually added via a different cohort.

Database tables affected:

Relating to courses:
* course
* course_director
* course_learning_material
* course_x_cohort
* course_x_discipline
* course_x_mesh
* course_x_objective

Relating to Sessions:
* session
* session_description
* session_learning_material
* session_x_discipline
* session_x_mesh
* session_x_objective

Relating to Offerings:
* offering
* offering_x_instructor
* offering_x_instructor_group

Steps and related SQL:

1. Get the course_id of the course to be duplicated.  This is "ORIGINAL_COURSE_ID".
2. Insert a new course into the course table using the ORIGINAL_COURSE_ID and a predetermined value for the columns 'year', 'start_date', 'end_date'.  The rest of the data will be populated from the original course:
```SQL
INSERT INTO course (course_level, year, start_date, end_date, locked, archived, school_id, published_as_tbd, clerkship_type_id, title) SELECT course_level, (year + 1) AS `year`, '2016-01-01' AS `start_date`, '2016-06-01' AS `end_date`, 0 AS `locked`, 0 AS `archived`, school_id, published_as_tbd, clerkship_type_id, title FROM course WHERE course_id = ORIGINAL_COURSE_ID;
```
This statement will insert the data into course table and create a new course_id value.  This value is "NEW_COURSE_ID".  Using NEW_COURSE_ID and ORIGINAL_COURSE_ID to add data to the other relevant course tables.

3. Add the course directors (course_director):
```SQL
INSERT INTO course_director SELECT NEW_COURSE_ID, user_id FROM course_director WHERE course_id = ORIGINAL_COURSE_ID;
```
4. Add the course learning materials (course_learning_material):
```SQL
INSERT INTO course_learning_material (course_id, learning_material_id, notes, required, notes_are_public) SELECT NEW_COURSE_ID, learning_material_id, notes, required, notes_are_public FROM course_learning_material WHERE course_id = ORIGINAL_COURSE_ID;
```
5. Add the course disciplines/topics (course_x_discipline):
```SQL
INSERT INTO course_x_discipline SELECT NEW_COURSE_ID, discipline_id FROM course_x_discipline WHERE course_id = ORIGINAL_COURSE_ID;
```
6. Add the course mesh terms (course_x_mesh):
```SQL
INSERT INTO course_x_mesh SELECT NEW_COURSE_ID, mesh_descriptor_uid FROM course_x_mesh WHERE course_id = ORIGINAL_COURSE_ID;
```
7. Add the course objectives (course_x_objective):
```SQL
INSERT INTO course_x_objective SELECT NEW_COURSE_ID, objective_id FROM course_x_objective WHERE course_id = ORIGINAL_COURSE_ID;
```
After these steps, the new course will have been added and it's time to add the sessions and offerings.  Where the courses were concerned there were only 2 variable values to necessary to track, NEW_COURSE_ID and ORIGINAL_COURSE_ID.  Where sessions and offerings are concerned, however, there will MULTIPLE sets of variables to track.
