### ISSUE TITLE
Handle shibboleth users with no account

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#780]
Currently using shibboleth authentication a user with valid shib credentials but no ilios account will be forced into a redirect loop.  We need to detect situations where a user is correctly authenticated with shibboleth, but does not have an ilios account and handle them gracefully.

Quick thought on handling this that needs more investigation:
Return JWT credentials for shibboleth users with an unauthenticated or authenticated: false attribute.  The frontend could then detect that flag and forward the sure to a No Account Found route.

**Comment by saschaben** [comment]
We should capture for:
- No Account in Ilios;
- Account in Ilios is good but disabled;
- Account in Ilios is somehow corrupt (invalid entries, duplication, bad I-don't-know-what);

I believe these are the three key routes that will need to be handled and returned to the shib user gracefully.

**Comment by mtb3** [comment]
Hi, I noticed this issue while browsing/searching through old issues that are still open, to assess their impact on my upcoming deployment.

From my testing with Ilios 3.13.0, I believe this issue is now resolved? Authenticating with Shibboleth, I see an error message in the UI for these cases:

- No account in Ilios
- Account in Ilios, but disabled

(I didn't test a wide variety of ways an account could be corrupt.)

**Comment by jrjohnson** [comment]
Thanks @mtb3 you are correct we fixed this in #832

**Comment by mtb3** [comment]
Great thanks for confirming.
