### ISSUE TITLE
Less Awful Scroll Bars on Month View Calendar

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#788]
This is the world's least important issue and I apologize for that.  I noticed that scroll bars appear where they are not needed on the month view of the calendar.  I actually scrolled on them to see if I was missing anything and felt stupid after doing so since clearly there is nothing else there.  See the screen shot below for reference.
![unnecessaryscrollbars](https://cloud.githubusercontent.com/assets/7493331/8881979/91750592-31f8-11e5-9fe9-03bdf8cd6b31.JPG)

**Comment by saschaben** [comment]
Yeah. This acutally is necessary in order to not hide the bottom listed events in a stack. We need to add significant white space there. This will be far less intrusive once we style the scrollbars (I am hoping we go with something like a 1 pixel line and a clean, sparse, small arrow-grab at top and bottom). So the enhancement really is to have less awful scrollbars in the calendar display.

**Comment by jrjohnson** [comment]
This was resolved by limiting the number of items in a month day.
