### ISSUE TITLE
Create Admin Landing Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#790]

**Comment by jenzweben** [comment]
First take at Admin Landing

Default State:
![admin-dash-v3](https://cloud.githubusercontent.com/assets/5023894/8917320/3234dd76-3466-11e5-893a-b05236116c08.png)

User Search:
![admin-dash-v3-search-open](https://cloud.githubusercontent.com/assets/5023894/8917328/40a30bee-3466-11e5-80ab-3cbf7a43e083.png)

**Comment by saschaben** [comment]
good start!

I'm not sure about concatenating unassigned accounts with sync exceptions in the same list: this would mean that for assignment to a cohort, we'd lose the ability to go to a list of users and "select all", and then go to a list of cohorts and pick a single destination in order to do bulk assignments (eg at the start of a new term with a fresh class of incoming students). Thoughts?

**Comment by jenzweben** [comment]
oh yeah - good point.  I'll fix that.  Anything else?

**Comment by saschaben** [comment]
not yet!

**Comment by jenzweben** [comment]
Take 2
![admin-dash-v4](https://cloud.githubusercontent.com/assets/5023894/8919524/e3cbd428-3474-11e5-9770-7630b0864118.png)

![admin-dash-v4-searchopen](https://cloud.githubusercontent.com/assets/5023894/8919529/ec9af4bc-3474-11e5-9460-3c7973c9245a.png)

**Comment by saschaben** [comment]
OK. thoughts:

1: The "possible Duplicates" label is misleading: there are half a dozen different potential errors that the exception list can catch. You can see the logic of the sync (if you want here https://www.dropbox.com/s/rsegnkfrdpjh18x/EDS_Non_Student_Ingest_Flowchart_draft.png?dl=0 and here https://www.dropbox.com/s/ixmcdcaefabctj2/EDS_Student_Ingest_Flowchart_draft.png?dl=0). The specific failure will need to be clear on a line by line, user by user basis. Also, one of the failures of the current UI is that the details of that error require an additional click and popup modal to be exposed; if we can handle that better it would be a real win.
2: on the unassigned: with your current mock, if I wanted to grab 25 unassigned users and drop them all into the Class of 2019 Cohort....how would I do that? We need a bulk model (many users to one target).
3: search. The global search is great, but how can that play well with seeking for a single record in one of the exception lists? do we need a search and sub-search fields? Filters?

**Comment by jenzweben** [comment]
Regarding search...my thought was that the number of line items in the Unassigned & Set User Roles lists would be small and that User Search would be more for one-off inquiries.  I'm also thinking that we might allow user to perform actions from a user detail page (i.e. if a user is Unassigned they could be assigned to a cohort either from the list or from their detail page...)

That being said, I don't think it's a deal breaker to add type-ahead filter / search in each section...

![admin-dash-v5](https://cloud.githubusercontent.com/assets/5023894/8944349/0cdbc7ae-3535-11e5-940c-a124d625680a.png)

**Comment by saschaben** [comment]
That all makes sense. Reality is that line items in the lists are usually in the dozen(s) range, but can and do grow to hundreds at the start of each year/term. Let's see what it would look like with search for each, and then make a decision on viability.

For the group unassigned, I think the mock will work, but we should discuss with @jrjohnson et al. the possibility of activating the bulk "select cohort" whenever more than one account is selected as well as for "select all". That tackles the case of "all minus one" as well as blocks of a few students per cohort (which is the more realistic case anyway).

for the sync exceptions list, I like the slide in of the user detail, but I don't think we can get away from a column that displays/describes the exception which is associated with the user. The users depend on their knowledge of what the error is in order to determine if action is needed (a user may have an expected exception --association with a different school than the one on record -- and therefore not need action, as opposed to the wrong email, which would require action, etc). One of the primary points of negative feedback in 2.4 around this feature is that they have to click on a user to find out the details of what went wrong in sync, rather than having it easily displayed. I don't know if there is an easy answer to this, but let's try one more round to see if we can get closer to what the users really really want.

**Comment by jenzweben** [comment]
OK I think I understand what you mean regarding showing the exception...how's this?

![admin-dash-v6](https://cloud.githubusercontent.com/assets/5023894/8995949/9336d8a8-36c9-11e5-915c-ccc512cca56c.png)

**Comment by saschaben** [comment]
that's it! OK -- let's move forward:  First the user detail page (includes role assignments, enabled/disabled status, former student status, sync exclusion, attributes of the user record, primary and secondary cohort assignments, per current display.

Then, the landing page with a view of: an entry in the sync exception list being selected to show details of  the user record with the exception;

and for the unassigned student list, showing the list of available cohorts activated.

**Comment by jenzweben** [comment]
Here's what I'm thinking for the User Detail page / module 

![admin-dash-v6-user-detail](https://cloud.githubusercontent.com/assets/5023894/9018608/5d0cb4ba-3795-11e5-8848-465a4d04cf27.png)

**Comment by jrjohnson** [comment]
I think this is the place to show associations as well. Groups / Offerings / Instructed Sessions / etc...  
Or is that a different user page?

**Comment by saschaben** [comment]
@jrjohnson I think we can get there, yes. First we need this to reflect the full basic account info though for display & management. We need to incorporate also the values for these additional fields (which can be updated by an admin user):
- allowing for sync exception;
- allow for disabling of account;
- allow for the addition of username/password values (for schools using the ilios native auth method);
- allow for (multiple) role assignment
- allow for clear display of student role
- allow for clear display of former student role
- allow for the assignment/display of  a primary school and one or more secondary schools;
- allow for the assignment/display of  a primary cohort and one or more secondary cohorts;

**Comment by jrjohnson** [comment]
Group thoughts:
Split up the user search, sync exception, and assignment into separate routes (Screens).  Place a sync and assignment table on the dashboard page with truncated (first 5 records) info and a link to go to the full controller for handling these issues.

The layout for each of these should look like the course page or program page table.

Add Admin navigation to the sliding menu for users which have that permission.  The admin dashboard would look like these mocks.

Considering not implementing 'activate rollover' links and just having those options in the action menus for course.  @saschaben will decide on this post haste.

**Comment by saschaben** [comment]
assigning to @jrjohnson as part of the initial user admin buildout

**Comment by dartajax** [comment]
Relates to #684

**Comment by saschaben** [comment]
closing in favor of #684.
